"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type ActiveVisit = { id: string; studentName: string; studentId: string; date: string; day: string; timeIn: string; purpose: string };

export default function Home() {
  const [form, setForm] = useState({ studentName: "", studentId: "", purpose: "" });
  const [activeVisit, setActiveVisit] = useState<ActiveVisit | null>(null);
  const [message, setMessage] = useState<{ text: string; kind: "success" | "error" } | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => { const saved = window.sessionStorage.getItem("active-lab-visit"); if (saved) window.setTimeout(() => setActiveVisit(JSON.parse(saved)), 0); }, []);
  async function markTimeIn(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(null); try { const response = await fetch("/api/attendance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (response.status === 409 && data.record) { const visit = { ...data.record, id: data.record.id }; setActiveVisit(visit); window.sessionStorage.setItem("active-lab-visit", JSON.stringify(visit)); setForm({ studentName: visit.studentName, studentId: visit.studentId, purpose: visit.purpose }); setMessage({ text: `${data.error} Your Time In was ${visit.timeIn}.`, kind: "error" }); return; } if (!response.ok) throw new Error(data.error); const visit = { ...data.record, id: data.record.id }; setActiveVisit(visit); window.sessionStorage.setItem("active-lab-visit", JSON.stringify(visit)); setForm({ studentName: visit.studentName, studentId: visit.studentId, purpose: visit.purpose }); setMessage({ text: `${data.message} Your Time In is ${visit.timeIn}.`, kind: "success" }); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Could not mark Time In.", kind: "error" }); } finally { setLoading(false); } }
  async function markTimeOut() { if (!activeVisit) return; setLoading(true); setMessage(null); try { const response = await fetch(`/api/attendance/${activeVisit.id}`, { method: "PATCH" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage({ text: `${data.message} Your Time Out is ${data.timeOut}.`, kind: "success" }); setActiveVisit(null); window.sessionStorage.removeItem("active-lab-visit"); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Could not mark Time Out.", kind: "error" }); } finally { setLoading(false); } }
  return <main className="student-shell"><div className="student-grid"><section className="intro-panel"><div className="brand-mark">CL</div><p className="eyebrow">Student access</p><h1>Computer Lab<br /><em>Attendance</em><br />&amp; In-Out Register</h1><p className="intro-copy">A quick, secure way to record your lab visit. Enter your details once when you arrive, then mark your departure before you leave.</p><div className="time-note"><span className="live-dot" /> Pakistan Standard Time<br /><strong>Asia / Karachi</strong></div></section><section className="form-card"><div className="card-heading"><div><p className="eyebrow">Lab visit</p><h2>Mark your attendance</h2></div><span className="date-chip">Auto dated</span></div>{message && <div className={`notice ${message.kind}`} role="status">{message.text}</div>}<form onSubmit={markTimeIn}><label>Student Name<input required value={form.studentName} disabled={Boolean(activeVisit)} onChange={(e) => setForm({ ...form, studentName: e.target.value })} placeholder="e.g. Ali Ahmed" /></label><label>Student ID / Roll No.<input required value={form.studentId} disabled={Boolean(activeVisit)} onChange={(e) => setForm({ ...form, studentId: e.target.value })} placeholder="e.g. BSN-102" /></label><label>Purpose of visit<textarea required rows={3} value={form.purpose} disabled={Boolean(activeVisit)} onChange={(e) => setForm({ ...form, purpose: e.target.value })} placeholder="What are you working on today?" /></label>{!activeVisit ? <button className="primary-button" disabled={loading}>{loading ? "Saving..." : "MARK TIME IN"}<span>↗</span></button> : <div className="active-visit"><div><span className="status-pill">● Active visit</span><p>Time In: <strong>{activeVisit.timeIn}</strong></p></div><button type="button" className="out-button" onClick={markTimeOut} disabled={loading}>{loading ? "Saving..." : "MARK TIME OUT"}<span>↗</span></button></div>}</form><p className="privacy-note">Your attendance is recorded with the server time and cannot be manually edited.</p></section></div><footer><span>Computer Lab Register</span><Link href="/admin">Admin sign in <span>→</span></Link></footer></main>;
}
